### ISSUE TITLE
Feature: Publish Level

### ISSUE THREAD

**Issue by Bolrik** [LPGameDevs/EditarrrPublic#25]
**Description**

I think in order to publish a level there should at least be validation by the creator.
To do this, the creator should have completed his level himself before publication.

Any changes made after completion again mark the level as unfinished and require another playthrough.

**ToDo**

- [ ] Add Validation-Flag to `EditorLevel.cs`
- [ ] When a Level is changed, Set Validation-Flag to false
- [ ] Before publish, Check for Validation-Flag
- [ ] (polish) Indicate Validation-Flag in Editor

**Comment by yanniboi** [comment]
Yup I agree. This is a very elegant solution to level validation. You could go down the route of checking there is a player in the level and a treasure chest and etc etc etc. But none of that matters if the creator has completed their game. This will also block people submitting impossibly difficult games (unless they are impossibly good ;) )

I would say that once we have time tracking for levels we should also track the creators best completion time so we can set that as a "par time" or something similar to put on the level search. So if people only want to play quick levels they can sort by how long a level takes to complete and ignore longer more complicated levels.
