### ISSUE TITLE
Level Selection Scene

### ISSUE THREAD

**Issue by yanniboi** [LPGameDevs/EditarrrPublic#6]
### Purpose

This scene is primarily about selecting what to do in the game. It has the following features:

- Create a new level
- Browse the list of local levels
- Play any of the local levels
- Download new level from remote server (TBC)
- Delete local levels to make space

### Current state

The scene exists in structure, however has no working functionality. (`Assets/_Project/Scenes/EditorSelection.unity`)

### Todo

- [x] Build out prefabs for levels
- [x] Scene transition to Edit or Play levels
- [x] Fix UI buttons for level prefabs and level selection.
- [x] Update level selection scripts to correctly set properties on Prefabs (`LevelSelectionLoader::DestroyAndRefreshLevels()`)
- [ ] General polish and styling.
