### ISSUE TITLE
Level Editor Scene

### ISSUE THREAD

**Issue by yanniboi** [LPGameDevs/EditarrrPublic#7]
### Purpose

The purpose of this scene is to allow the user place tiles on a canvas and build out the structure of the level they are working on. They can save their progress and easily switch between playing and editing to evaluate their level.

### Current state

The scene exists (`Assets/_Project/Scenes/DemoScene.unity`) and has all the features for selecting and placing tiles. It doesnt have the ability to save or play the level yet.

### Todo

- [x] UI for saving/resetting the level.
- [x] UI for testing the level.
- [x] UI for return to level selection.
- [x] General polish and styling.
