### ISSUE TITLE
Level Play Scene

### ISSUE THREAD

**Issue by yanniboi** [LPGameDevs/EditarrrPublic#8]
### Purpose

The purpose of this scene is to play the levels. Either to test your current work in progress or to play and review other people's levels. 

### Current state

This scene doesn't exist yet. It will be a clone of the the Editor scene (#7) but with some changes to level background and the `TilePainter` class. It will also need a UI timer and Win screen.

### Todo

- [x] Clone Editor scene
- [x] Update `TilePainter.cs` for playing the level.
- [x] Spawn the player on level start.
- [x] UI for timer and win conditions
- [x] UI for exit/restart/back to editing
